<html>
<head></head>
<body>
	<div>
		<p><?php echo $this->row->usuario_nome; ?>,</p>
		
		<p>
			Voc&ecirc; acaba de receber sua nova senha, utilize os dados abaixo
			para ter acesso novamente ao web site.
		</p>
		
		<p>
			<strong>Usu&aacute;rio:</strong> <?php echo $this->row->usuario_login; ?><br />
			<strong>Senha:</strong> <?php echo $this->password; ?>
		</p>
		
		<p>Muito Obrigado.</p>
	</div>
</body>
</html>