<div class="mainTela">
    <div dojoType="dijit.layout.BorderContainer" class="borderToolbar">
        <?php 
		echo $this->toolbar()
			  ->addCustomButton(
			    array(
				'id'     => 'button-detalhar-auditoria',
				'label'  => 'Detalhar',
				'icon'   => 'icon-toolbar-zoom',
				'click'  => 'masterAuditoria.detalhar();'
			    )
			  );
	?>
    </div>
    <div id="gridMasterAuditoria" class="gridTela"></div>
    <div id="divpagMasterAuditoriaGrid" class="pagingBlock"></div>
</div>