<?php 
$totalProjeto = 0;
$totalProjetoParaProjeto = 0;
$crtlProjeto = 0;
foreach ( $this->data as $tipoLanc ) :

    $crtl = 0 ;
    $totalTipoLanc = 0;
    $totalTipoLancProjeto = 0;
    foreach ( $tipoLanc as $item ) : 
        if(empty($crtlProjeto)){

            if(!empty( $item->projeto_id)){

                $strProjeto = 'Projeto - '.$item->projeto_nome;
            }else{

                 $strProjeto = 'Lançamentos com nenhum projeto vinculado';
            }
            
            $strTr = '<tr><td colspan="8"><font size="12">'.$strProjeto.'</font></td></tr>';
            if($_SESSION['Header_Projeto']){
                
                echo '<tr><td>&nbsp;</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>';
                echo '<tr><td>&nbsp;</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>';
                echo $strTr;
            }else{
                
                echo $strTr;
                $_SESSION['Header_Projeto'] = true;
            }
?>
            <tr>
                <th><?php echo $this->translate()->_( 'Data' ); ?></th>
                <th><?php echo $this->translate()->_( 'N. do documento' ); ?></th>
                <th><?php echo $this->translate()->_( 'Remetente' ); ?></th>
                <th><?php echo $this->translate()->_( 'Memória' ); ?></th>
                <th><?php echo $this->translate()->_( 'Conta' ); ?></th>
                <th><?php echo $this->translate()->_( 'Fluxo' ); ?></th>
                <th><?php echo $this->translate()->_( 'Valor do documento' ); ?></th>
                <th><?php echo $this->translate()->_( 'Valor Para o Projeto' ); ?></th>
            </tr>
<?php
            }
            $crtlProjeto++;
            if(empty($crtl)){

                $cod =  (empty( $item->fn_tipo_lanc_cod  )? '' : $item->fn_tipo_lanc_cod.' - ' );
                if(!empty( $item->fn_tipo_lanc_desc) || !empty( $item->fn_tipo_lanc_desc)){
                    
                    $strTipoLanc = $cod.$item->fn_tipo_lanc_desc;
                }else{
                    
                    $strTipoLanc = 'Lançamentos com nenhum tipo de lançamento vinculado';
                }
                echo '<tr><th colspan="8">'.$strTipoLanc.'</th></tr>';
            }
            $crtl++;
            
            if ( 'C' == $item->fn_lancamento_tipo ){

                $totalProjeto += (float)$item->fn_lancamento_valor;
                $totalProjetoParaProjeto += (float)$item->fn_lanc_projeto_valor;
                $totalTipoLanc += (float)$item->fn_lancamento_valor;
                $totalTipoLancProjeto += (float)$item->fn_lanc_projeto_valor;
            }else{

                $totalProjeto -= (float)$item->fn_lancamento_valor;
                $totalProjetoParaProjeto -= (float)$item->fn_lanc_projeto_valor;
                $totalTipoLanc -= (float)$item->fn_lancamento_valor;
                $totalTipoLancProjeto -= (float)$item->fn_lanc_projeto_valor;
            }
?>
            <tr>
                <td><?php echo $this->date( $item->fn_lancamento_dtefetivado ); ?></td>
                <td><?php echo (empty($item->fn_doc_fiscal_numero) ? '-' : $item->fn_doc_fiscal_numero); ?></td>
                <td><?php echo (empty($item->terceiro_nome_remetente) ? '-' : $item->terceiro_nome_remetente); ?></td>
                <td><?php echo (empty($item->fn_lancamento_obs) ? '-' : $item->fn_lancamento_obs); ?></td>
                <td><?php echo $item->fn_conta_descricao; ?></td>
                <td><?php echo $this->nomenclatura()->tipoLancamento( $item ); ?></td>
                <td><?php echo $this->currency( ( 'C' == $item->fn_lancamento_tipo ? 1 : -1 ) * $item->fn_lancamento_valor ); ?></td>
                <td><?php echo $this->currency( ( 'C' == $item->fn_lancamento_tipo ? 1 : -1 ) * $item->fn_lanc_projeto_valor ); ?></td>
            </tr>
<?php
    endforeach;
    echo '<tr><td colspan="6"><b>Total em '.$strTipoLanc.'</b></td><td>'.$this->currency( $totalTipoLanc ).'</td><td>'.$this->currency( $totalTipoLancProjeto ).'</td></tr>';
endforeach;

    echo '<tr><td colspan="6"><b>Total em <b>'.$strProjeto.'</b></td><td>'.$this->currency( $totalProjeto ).'</td><td>'.$this->currency( $totalProjetoParaProjeto ).'</td></tr>';
?>