<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" >

<style type="text/css">
    body, html {
	font-family: Verdana;
	font-size: 14px;
	margin: 0;
    }
    
    .recibo-container {
	width: 100%;
	margin: 10px 10px;
    }
    
    .recibo-endereco {
	color: #aaa;
	text-align: center;
	font-size: 14px;
    }
    
    h3 {
	text-align: center;
	text-decoration: underline;
	text-transform: uppercase;
    }
    
    .table-recibo {
	width: 100%;
    }
    
    .table-recibo td {
	padding: 3px;
    }
    
    .label {
	width: 80px;
    }
    
    .text {
	text-transform: uppercase;
	border: 1px solid;
	border-width: 0 0 1px 0;
    }
    
    .data {
	width: 100px;
	text-align: center;
    }
   
</style>

<?php echo $this->partialLoop( 'recibo.phtml', $this->recibos->toArray() ) ; ?>