<div class="mainTela">
    <div dojoType="dijit.layout.BorderContainer" class="borderToolbar">
        <?php 
            echo $this->toolbar()
                ->addCustomButton(
                    array(
                        'action' => App_Plugins_Acl::getIdentifier( '/gestao/timeline/', 'Custo' ),
                        'id'     => 'button-custo-timeline',
                        'label'  => 'Custo',
                        'icon'   => 'icon-toolbar-coinsadd',
                        'click'  => 'gestaoTimeline.custo();'
                       )
                 )
                    ->addCustomButton(
                       array(
                        'action' => App_Plugins_Acl::getIdentifier( '/gestao/timeline/', 'Lancamento' ),
                        'id'     => 'button-lancamento-timeline',
                        'label'  => 'Lançamento',
                        'icon'   => 'icon-toolbar-coinsadd',
                        'click'  => 'gestaoTimeline.lancamento();'
                    )
                 );  
        ?>
    </div>
    
    <div id="scheduler_here" class="dhx_cal_container" style='width:100%; height:100%;'>
        <div class="dhx_cal_navline">
            <div class="dhx_cal_prev_button">&nbsp;</div>
            <div class="dhx_cal_next_button">&nbsp;</div>
            <div class="dhx_cal_today_button"></div>
            <div class="dhx_cal_date"></div>

            <div class="dhx_cal_tab" name="day_tab" style="right:204px;"></div>
            <div class="dhx_cal_tab" name="week_tab" style="right:140px;"></div>
            <div class="dhx_cal_tab" name="month_tab" style="right:76px;"></div>
        </div>
        <div class="dhx_cal_header">
        </div>
        <div class="dhx_cal_data">
        </div>
    </div>

    
</div>
