<div class="mainTela">
    <div dojoType="dijit.layout.BorderContainer" class="borderToolbar">
        <?php 
		echo $this->toolbar()
			  ->addCustomButton(
			    array(
				'action' => App_Plugins_Acl::getIdentifier( '/financeiro/lancamento-cartao/', 'Reconciliar' ),
				'id'     => 'button-reconciliar-cartao',
				'label'  => 'Reconciliar',
				'icon'   => 'icon-toolbar-pagerefresh',
				'click'  => 'financeiroLancamentoCartao.reconciliar();'
			    )
			  );  
	?>
    </div>
    <div id="gridFinanceiroLancamentoCartao" class="gridTela"></div>
    <div id="divpagFinanceiroLancamentoCartaoGrid" class="pagingBlock"></div>
</div>