<div id="dialogBuscaCheque"
     title="<?php echo $this->translate()->_('Cheque'); ?>"
     style="display:none;"
     dojoType="dijit.Dialog">
    <table>
        <tr>
            <td align="center" colspan="4" height="220px" width="650px">
				<div id="gridBuscaFinanceiroCheque" class="gridTela"></div>
				<div id="divpagBuscaFinanceiroChequeGrid" class="pagingBlock"></div>
            </td>
        </tr>
    </table>
</div>
