<tr>
    <th><?php echo $this->translate()->_('Conta'); ?></th>
    <th><?php echo $this->translate()->_('Data Inicial'); ?></th>
    <th><?php echo $this->translate()->_('Saldo Inicial'); ?></th>
    <th><?php echo $this->translate()->_('Data Final'); ?></th>
    <th><?php echo $this->translate()->_('Saldo Final'); ?></th>
    <th><?php echo $this->translate()->_('Situação'); ?></th>
    <th><?php echo $this->translate()->_('Data Efetivação'); ?></th>
</tr>
<tr>
    <td><?php echo $this->data->fn_conta_descricao; ?></td>
    <td><?php echo $this->date($this->data->fn_recon_ini_data); ?></td>
    <td><?php echo $this->currency($this->data->fn_recon_ini_valor); ?></td>
    <td><?php echo $this->date($this->data->fn_recon_fim_data); ?></td>
    <td><?php echo $this->currency($this->data->fn_recon_fim_valor); ?></td>
    <td><?php echo $this->nomenclatura()->situacaoReconciliacaoBancaria($this->data); ?></td>
    <td><?php echo $this->date($this->data->fn_recon_dtefetivada); ?></td>
</tr>
<tr>
    <th rowspan="<?php echo count($this->itens) + 1; ?>">
        <?php echo $this->translate()->_('Lançamentos'); ?>
    </th>
    <th><?php echo $this->translate()->_('Data'); ?></td>
    <th colspan="2"><?php echo $this->translate()->_('Doc. Fiscal'); ?></td>
    <th><?php echo $this->translate()->_('Tipo'); ?></td>
    <th><?php echo $this->translate()->_('Situação'); ?></td>
    <th><?php echo $this->translate()->_('Valor'); ?></td>
</tr>

<?php
    $total = 0;
    foreach ($this->itens as $item) : 
        
        if($item->fn_lancamento_tipo == 'D'){
            
            $total = $total-$item->fn_lancamento_valor;
        }else{
            
            $total = $total+$item->fn_lancamento_valor;
        }
?>


    <tr>
        <td><?php echo $this->date($item->fn_lancamento_dtefetivado); ?></td>
        <td colspan="2"><?php echo (empty($item->fn_lancamento_trans) ? $item->fn_doc_fiscal_numero : 'Transfer&ecirc;ncia'); ?></td>
        <td><?php echo $this->nomenclatura()->tipoLancamentoBancario($item); ?></td>
        <td><?php echo $this->nomenclatura()->situacaoReconciliacaoBancaria($item); ?></td>
        <td><?php echo ( $item->fn_lancamento_tipo == 'D' ? '- ': '').$this->currency($item->fn_lancamento_valor); ?></td>
    </tr>
<?php endforeach; ?>
        <tr>
            <td colspan="4">
                <?php echo $this->translate()->_('Total'); ?>
            </td>
            <td colspan="2">
                <strong>
                    <?php echo $this->currency($total); ?>
                </strong>
            </td>
        </tr>