<table id="relatorio">
	<thead>
		<tr>
			<th><?php echo $this->translate()->_( 'Emissão' ); ?></th>
			<th><?php echo $this->translate()->_( 'Para' ); ?></th>
			<th><?php echo $this->translate()->_( 'Emitido Para' ); ?></th>
			<th><?php echo $this->translate()->_( 'Situação' ); ?></th>
			<th><?php echo $this->translate()->_( 'Banco' ); ?></th>
			<th><?php echo $this->translate()->_( 'Conta' ); ?></th>
			<th><?php echo $this->translate()->_( 'Número' ); ?></th>
			<th><?php echo $this->translate()->_( 'Valor' ); ?></th>
		</tr>
	</thead>

    <tbody>
		<?php echo $this->partialLoop( 'cheque/row.phtml', $this->data['data'] ); ?>
	</tbody>
	
	<tfoot>
    	<tr>
		    <td colspan="6">
				<?php echo $this->translate()->_( 'Total' ); ?>
		    </td>
		    <td colspan="2">
		    	<strong>
		    		<?php echo $this->currency( $this->data['total'] ); ?>
		    	</strong>
		    </td>
    	</tr>
    </tfoot>
</table>