<div class="mainTela">
    <div dojoType="dijit.layout.BorderContainer" class="borderToolbar">
        <?php 
	      echo $this->toolbar()
			->addCustomButton(
				array(
				    'id'     => 'button-detalha-lembrete',
				    'label'  => 'Detalhar',
				    'icon'   => 'icon-toolbar-emailopenimage',
				    'click'  => 'defaultLembrete.detalhaLembreteGrid();'
				)
			); 
	?>
    </div>
    <div id="gridDefaultLembrete" class="gridTela"></div>
    <div id="divpagDefaultLembreteGrid" class="pagingBlock"></div>
</div>