<div class="mainTela">
    <div dojoType="dijit.layout.BorderContainer" class="borderToolbar">
        <?php 
		echo $this->toolbar()
			  ->addCustomButton(
			    array(
				'action' => App_Plugins_Acl::getIdentifier( '/master/menu/', 'Organizar' ),
				'id'     => 'button-organizar-menu',
				'label'  => 'Organizar',
				'icon'   => 'dijitIconFilter',
				'click'  => 'masterMenu.organizar();'
			    )
			  );  
	?>
    </div>
    <div id="gridMasterMenu" class="gridTela"></div>
    <div id="divpagMasterMenuGrid" class="pagingBlock"></div>
</div>